### ISSUE TITLE
All ESD profiles are deleting when removing just one

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#1044]
#### Agent Version
All supported with ESD

#### Operating System
N/A

#### OpenStack Release
All supported

#### Description
There is a bug in the case multiple ESDs are applied. The agent deletes all ESD profiles on the device (but not in Neutron) when any of the ESD’s are removed. This has led to downtime as the device configuration (iRule or profile, profile) is unexpectedly changed from the desired state.

#### Deployment
N/A

**Comment by pjbreaux** [comment]
Partly, this is an ordering issue in the agent code. When we loop through the L7 policies to apply (whether they are ESD policies or not), we are not adhering the 'position' field of the policy. This dictates the priority of the policy itself. In the case of multiple policies, then subsequent policy that is evaluated can overwrite settings from prior policies applied. The other part of this issue is that we will have to determine whether multiple ESD policies should produce an aggregate result or if some other rules should apply.
