### ISSUE TITLE
Edit agent ini file for typos, branding, spelling, clarity

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-agent#171]
#### OpenStack Release

Liberty +
#### Description

The agent ini file has a number of typos, misspellings, etc. that should be corrected. Once these changes are made, the examples in f5-openstack-lbaasv2-driver need to be updated to match.
##### Specific edits:
- In L2 Segmentation Mode settings, the heading Device Tunneling (VTEP) "selfips" is used twice

**Comment by alonsocamaro** [comment]
Hi 

I find the following should be clarified too:

```

# icontrol_hostname is valid for external device type only.
# this setting can be either a single IP address or a 
# comma separated list contain all devices in a device 
# service group.  For guest devices, the first fixed_address
# on the first device interfaces will be used.

```

- Does "device service group" really stand for "device group" ?

- The sentence "icontrol_hostname is valid for external device type only." Is confusing because it doesn't leave any option left open on how to contact the BIG-IP VE 

- Also the paragraph afterwards this would be more clear if written the following: if setting up a standalone device then, if it is hapair then... , if "scalen" is configured then... It is a bit confusing the way it is written.

**Comment by jputrino** [comment]
The following section needs to be re-written for clarity:
```
# icontrol_hostname is valid for external device type only.
# this setting can be either a single IP address or a 
# comma separated list contain all devices in a device 
# service group.  For guest devices, the first fixed_address
# on the first device interfaces will be used.
#
# If a single IP address is used and the HA model 
# is not standalone, all devices in the sync failover
# device group for the hostname specified must have 
# their management IP address reachable to the agent.
# If order to access devices' iControl® interfaces via
# self IPs, you should specify them as a comma
# separated list below.
```

**Comment by richbrowne** [comment]
Fixed.
