### ISSUE TITLE
RPM package installation fails

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-agent#494]
#### Agent Version
9.2.0.b1

#### Operating System
CentOS7

#### OpenStack Release
Mitaka

#### Description
Agent RPM installation fails due to dependency problems.  F5-SDK now requires ordereddict and six, which are not specified as RPM dependencies in the F5-SDK RPM.  That in turn causes the Agent RPM to fail during installation.

#### Deployment
N/A

#### Workaround
Manually download and install ordereddict and six RPM packages.  Then install the Agent RPM package, which verifies/installs the appropriate F5-SDK RPM package.

**Comment by ssorenso** [comment]
This issue was actually root caused to [f5-common-python 933](https://github.com/F5Networks/f5-common-python/issues/933) causing the rpm and deb packages created by this repo (f5-sdk). The fix here is to fix the automated detection of issues with the .rpm or .deb packages created here in the agent.

Logic of this isolation is as follows:

- Agent does not require the two libraries mentioned in the description
- SDK does and is a dependent of the Agent
- SDK depends on the f5-icontrol-rest; however, it, too, does not rely on the two modules mentioned in the description

**Comment by ssorenso** [comment]
This issue was fixed with https://github.com/F5Networks/f5-openstack-agent/pull/556
