### ISSUE TITLE
Explicitly document environment_prefix max length

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-agent#517]
Differentiated environment docs need to explicitly state the max string length for environment prefix is 8 characters.

#### OpenStack Release
Liberty

#### Description
Just add a note to the docs to state that the character limit for environment prefix is 8.  Add this to the
ini file as well.

#### Agent Version
8.0.2.b1

#### Operating System
Any

#### OpenStack Release
Liberty, Mitaka ...

**Comment by richbrowne** [comment]
Assigning to Matt, but I can take this.  i just wanted to make you aware of it.

**Comment by mattgreene** [comment]
@richbrowne: Make this issue the documentation of the limitation.  We will include a link to the issue in the 'Caveats' section of the release notes for the next release.  A future bug will programmatically enforce the length limitation, and we'll close this bug as well since the 'product' will let the user know there is a problem with their input.

**Comment by richbrowne** [comment]
Documented in the differentiated environments docs.

**Comment by jputrino** [comment]
Issue moved to [F5Networks/f5-openstack-docs #238](https://github.com/F5Networks/f5-openstack-docs/issues/238) via [**ZenHub**](https://www.zenhub.com/)
