### ISSUE TITLE
Agent expects to add fdb entries for each pool member port that exists

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-agent#754]
#### OpenStack Release
liberty

#### Description
[Here](https://github.com/F5Networks/f5-openstack-agent/blob/liberty/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py#L699), the agent will add forwarding database entries for each pool member added to a pool. This means that it is expecting information from the member's port to create those fdb entries. With the new change to ignore port existence, we allow that member to get to the network_service.py without a port. If no port is found, the member's provisioning status is set to ERROR. Note that this is also the case when we are [deleting a member](https://github.com/F5Networks/f5-openstack-agent/blob/liberty/f5_openstack_agent/lbaasv2/drivers/bigip/network_service.py#L712) as well. This is causing at least two tests to fail in the driver. Those are:

```
api.test_member_status.memberstatustestjson.test_no_monitor								
api.test_member_status.memberstatustestjson.test_online
```

Note that I included that this issue exists in liberty, so the fix should go there and be merged forward. In my preliminary testing, I just log a warning, and this suffices, but I would like to see what @jlongstaf and @szakeri thinks. I can get the test to pass this way, but I know now that we need a specific test in the driver or agent in liberty that checks member provisioning_status, as well as loadbalancer status. I did not find this issue, until I started running the above tests (in jenkins) in the mitaka branch.

**Comment by jgruber** [comment]
The LBaaSv2 specification for a pool member requires 4 items:

subnet - a valid Neutron subnet uuid
address - a valid IPv4 or IPv6 address
protocol-port - an int between 1-65535
pool - a valid pool uuid

The reference implementation does not demand that a port be present for the pool member. It does not even validate that the address given is part of the subnet uuid provided. We should support what the reference implementation supports if you want to pass community tests now and into the future. That means not only relaxing the need for a port, but also relaxing the validation of the IP being in the subnet defined by the UUID. 

In LBaaSv1 you could simply provide an IP address. In the service driver we would attempt to discover if the address was

- part of a subnet owned by the tenant creating the pool member 
- part of a shared subnet 
- just a random IP 

Only if we found it on a subnet did we add port information or try to find the VTEP address (thus fdb record) for the pool member. I assumed this was removed because it required us to query the neutron DB directly. 

If it was on a shared network, we decorated the subnet with route domain 0.
If it was just a random IP, we decorated the subnet with route domain 0.

**Comment by pjbreaux** [comment]
@jgruber: I believe the validation code you speak of was in the driver and was removed. Is this the change you were suggesting: https://github.com/F5Networks/f5-openstack-lbaasv2-driver/commit/801cd8543e0881ba28d4bc4b095809a0eec8e756
